type User @table {
  displayName: String!
  email: String!
  role: String!
  createdAt: Timestamp!
  photoUrl: String
  phoneNumber: String
}

type MenuItem @table {
  name: String!
  price: Float!
  category: String!
  isAvailable: Boolean!
  createdAt: Timestamp!
  description: String
  allergens: [String]
  imageUrl: String
}

type Order @table {
  user: User
  orderDate: Date!
  status: String!
  totalAmount: Float!
  createdAt: Timestamp!
  pickupTime: Timestamp
}

type OrderItem @table {
  order: Order
  menuItem: MenuItem
  quantity: Int!
  unitPrice: Float!
  notes: String
  subtotal: Float
}

type Ingredient @table {
  name: String!
  currentStock: Float!
  unit: String!
  minimumStockLevel: Float!
  createdAt: Timestamp!
  supplier: String
}